### ISSUE TITLE
Legibility of screen

### ISSUE THREAD

**Issue by icr-ctl** [conservationtechlab/dencam#59]
With our OLL unit that is in the glaring SoCal sun, only the yellow text on the solar info page is easily legible. For at least this unit, we should switch all UI pages to yellow, I think. Maybe that would be best for Svalbard units, too (and thus be the default in the code)? Note: we could make the color scheme configurable from settings in the config file.

**Comment by kgarwoodsdzwa** [comment]
simultaneously add titles to the respective display pages on the screen
